---
# useful for debugging
log: true


instapaper_username: username
instapaper_password: password

# also count unread items in folders
instapaper_folders:
  - folder
  - another folder

# append unread count to this file instead of stdout
instapaper_output: "instapaper.txt"


