---
username: "usernmae"
password: "password"

# also count unread items in folders
include_folders:
  - economist
  - other folder

# useful for debugging
log: true

# append unread count to this file instead of stdout
output: "unread.txt"
