---
# useful for debugging
log: true


instapaper_username: username
instapaper_password: password

# also count unread items in folders
instapaper_folders:
  - folder
  - another folder

# append unread count to this file instead of stdout
instapaper_output: "instapaper.txt"


# imap inbox counting
imap_server: imap.gmail.com
imap_port: 993
imap_ssl: true
imap_username: username
imap_password: password
imap_folders: [] # not supported yet
imap_output: "imap.txt" # write count to this file

# count unread mails, or total number of mails in inbox (I file handled mail in an archive folder)
imap_unread_only: false 
